name: Export PCO Data

on:
  workflow_dispatch:

jobs:
  export-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      id: run_script
      run: |
        OUTPUT=$(python export_pco_data.py)
        echo "CSV_PATH=$OUTPUT" >> $GITHUB_ENV

    - name: List files in the current directory
      run: ls -la

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pco_data
        path: ${{ env.CSV_PATH }}
